name: Sync Mirror
inputs:
  server:
    required: true
  user:
    required: true
  path:
    required: true
  key:
    required: true
  pat:
    required: true
  cache:
    required: false
    default: true
runs:
  using: composite
  steps:
    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: registry.eeems.codes
        username: github
        password: ${{ inputs.pat }}
    - uses: actions/setup-python@v5
      continue-on-error: true
      with:
        python-version: '3.11'
        cache: 'pip'
    - run: pip install -r requirements.txt
      shell: bash
    - uses: jpribyl/action-docker-layer-caching@v0.1.1
      if: ${{ inputs.cache && inputs.cache != 'false' }}
      continue-on-error: true
      with:
        key: image-eeems/archlinux:latest-{hash}
        restore-keys: |
          image-eeems/archlinux:latest-
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        path: repo
        merge-multiple: true
    - name: Rsync
      if: ${{ matrix.runner != 'self-hosted' }}
      run: python -u ./scripts/build.py mirror "${{ inputs.user }}@${{ inputs.server }}:${{ inputs.path }}"
      shell: bash
      env:
        VERBOSE: 1
        GITHUB_ACTIONS: 1
        SSH_KEY: ${{ inputs.key }}
    - name: Rsync self-hosted
      if: ${{ matrix.runner == 'self-hosted' }}
      run: python -u ./scripts/build.py mirror --image "registry.eeems.codes/archlinux:latest" "${{ inputs.user }}@${{ inputs.server }}:${{ inputs.path }}"
      shell: bash
      env:
        VERBOSE: 1
        GITHUB_ACTIONS: 1
        SSH_KEY: ${{ inputs.key }}
