name: Sync Mirror
description: Sync Mirror
inputs:
  server:
    description: Server to mirror to
    required: true
  user:
    description: User to connect to server as
    required: true
  path:
    description: Path to put the mirror
    required: true
  key:
    description: SSH key to use
    required: true
  pat:
    description: GitHub PAT
    required: true
  ssh:
    description: Extra args to pass to ssh
    required: false
  cache:
    description: If docker layer caching should be used when mirroring
    required: false
    default: true
runs:
  using: composite
  steps:
    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: registry.eeems.codes
        username: github
        password: ${{ inputs.pat }}
    - uses: actions/setup-python@v5
      continue-on-error: true
      with:
        python-version: "3.11"
        cache: "pip"
    - run: pip install -r requirements.txt
      shell: bash
    - uses: jpribyl/action-docker-layer-caching@v0.1.1
      if: ${{ inputs.cache && inputs.cache != 'false' }}
      continue-on-error: true
      with:
        key: image-eeems/archlinux:latest-{hash}
        restore-keys: |
          image-eeems/archlinux:latest-
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        path: repo
        pattern: repo-*
        merge-multiple: false
    - name: Fix names
      shell: bash
      run: |
        find repo -maxdepth 1 -type d -name 'repo-*' -printf '%f\n' | while read -r repo; do
          mv repo/$repo repo/$(echo $repo | cut -d - -f 2-)
        done
    - name: Rsync
      if: ${{ matrix.runner != 'self-hosted' }}
      run: python -u ./scripts/build.py mirror "${{ inputs.user }}@${{ inputs.server }}:${{ inputs.path }}" --ssh "${{ inputs.ssh }}"
      shell: bash
      env:
        VERBOSE: 1
        GITHUB_ACTIONS: 1
        SSH_KEY: ${{ inputs.key }}
    - name: Rsync self-hosted
      if: ${{ matrix.runner == 'self-hosted' }}
      run: python -u ./scripts/build.py mirror --image "registry.eeems.codes/archlinux:latest" "${{ inputs.user }}@${{ inputs.server }}:${{ inputs.path }}" --ssh "${{ inputs.ssh }}"
      shell: bash
      env:
        VERBOSE: 1
        GITHUB_ACTIONS: 1
        SSH_KEY: ${{ inputs.key }}
