name: build
on:
    push:
        branches:
            - main
    schedule:
        - cron: '0 0 * * *'
jobs:
    build:
        name: Build latest
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Login to Docker Registry
              uses: docker/login-action@v1
              with:
                  registry: registry.eeems.codes
                  username: github
                  password: ${{ secrets.CR_PAT }}
            - uses: actions/setup-python@v2
              with:
                cache: 'pip'
            - run: pip install -r requirements.txt
            - name: Pacman cache
              uses: actions/cache@v2
              with:
                path: cache
            - name: Build repos
              run: python ./scripts/build.py repos
              env:
                  GPGKEY: ${{ secrets.GPGKEY }}
                  GPG_PRIVKEY: ${{ secrets.GPG_PRIVKEY }}
            - uses: actions/upload-artifact@v2
              with:
                name: packages
                path: packages
