name: build
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      build-matrix: ${{ steps.build-matrix.outputs.JSON_CONTENT }}
      repo-matrix: ${{ steps.repo-matrix.outputs.JSON_CONTENT }}
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        continue-on-error: true
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Get package list
        id: build-matrix
        run: |
          echo 'JSON_CONTENT<<EOF' >> $GITHUB_OUTPUT
          python ./scripts/build.py repos --json --stats >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Get repo list
        id: repo-matrix
        run: |
          echo 'JSON_CONTENT<<EOF' >> $GITHUB_OUTPUT
          python ./scripts/build.py repos --json >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
  build:
    name: Build ${{ matrix.repo }}/${{ matrix.package }}
    runs-on: ${{ matrix.runner }}
    continue-on-error: true
    needs: [setup]
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.build-matrix) }}
      fail-fast: false
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.eeems.codes
          username: github
          password: ${{ secrets.CR_PAT }}
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - uses: actions/setup-python@v4
        continue-on-error: true
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Pacman cache
        uses: actions/cache@v3
        with:
          path: cache
          key: ${{ runner.os }}
      - uses: jpribyl/action-docker-layer-caching@v0.1.1
        if: ${{ matrix.runner != 'self-hosted' }}
        continue-on-error: true
      - name: Build ${{ matrix.repo }}/${{ matrix.package }}
        timeout-minutes: 720
        run: |
          python -u ./scripts/build.py repos --package ${{ matrix.package }}
        env:
          GPGKEY: ${{ secrets.GPGKEY }}
          GPG_PRIVKEY: ${{ secrets.GPG_PRIVKEY }}
          WORKDIR: workdir
          DOCKER_PRUNE: 1
          GITHUB_ACTIONS: 1
          VERBOSE: 1
      - name: Sanitize filename
        run: |
          cd packages
          ls | while read file;do
            if [[ "$file" == *:* ]];then
              sudo mv "$file" "${file/:/_}"
            fi
          done
      - uses: actions/upload-artifact@v3
        with:
          name: packages-${{ matrix.repo }}
          path: packages
          if-no-files-found: error
  repo:
    name: Build repo
    runs-on: ubuntu-latest
    needs: [setup, build]
    strategy:
      matrix:
        repo: ${{ fromJson(needs.setup.outputs.repo-matrix) }}
      fail-fast: false
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: packages-${{ matrix.repo }}
          path: repo
      - name: Repo ${{ matrix.repo }}
        run: |
          python -u ./scripts/build.py repos --publish ${{ matrix.repo }}
        env:
          GPGKEY: ${{ secrets.GPGKEY }}
          GPG_PRIVKEY: ${{ secrets.GPG_PRIVKEY }}
          REPO_NAME: ${{ matrix.repo }}
      - uses: actions/upload-artifact@v3
        with:
          name: repo-${{ matrix.repo }}
          path: repo
          if-no-files-found: error
